### ISSUE TITLE
[Flicks] Assignment 1 - Review My App Please #1

### ISSUE THREAD

**Issue by Jaime5** [Jaime5/assignment-1-flicks#1]
The basics of my app are complete, please review. /cc @codepathreview

**Comment by codepathreview** [comment]
Hi,

It looks like you have not either finished all the requirements (3rd and 4th requirements) or pushed the latest code into your repo. Please update the code as soon as possible. We cannot review your work without your complete code.

Best.

**Comment by Jaime5** [comment]
Finished that part... sorry about the that
